version: '3.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - 5050:80
  migration-up:
    environment:
      NODE_OPTIONS: --loader ts-node/esm
    build:
      context: .
      target: development
    volumes:
      - ./:/user/app
    ports:
      - 3000:3000
    depends_on:
      - db
    command: npx knex migrate:up --knexfile ./src/db/knexfile.ts
  migration-down:
    environment:
      NODE_OPTIONS: --loader ts-node/esm
    build:
      context: .
      target: development
    volumes:
      - ./:/user/app/
    ports:
      - 3000:3000
    depends_on:
      - db
    command: npx knex migrate:down --knexfile ./src/db/knexfile.ts
  server:
    build:
      context: .
      target: development
    volumes:
      - ./:/user/app
    ports:
      - 3000:3000
    depends_on:
      - db
      - pgadmin
    command: npx nodemon --esm src/index.ts
